version: "3.7"

services:
  node:
    build:
      context: node
      target: node
    stdin_open: true
    tty: true
    working_dir: /app
    hostname: 0.0.0.0
    entrypoint:
      - npm
    command:
      - start
    ports:
      - 3000:3000
    volumes:
      - ./node/src:/app/src
      - ./node/public:/app/public
      - /app/node_modules

  app:
    build:
      context: app
      target: app
    stdin_open: true
    tty: true
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 3 --reload
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./app/src:/code
    env_file:
      - ./app/envs/dev.env

  postgres:
    image: postgres:11.4
    environment:
      POSTGRES_DB: dmtools
      POSTGRES_USER: dm
      POSTGRES_PASSWORD: beholder
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
