version: "3.7"

services:
  node:
    build:
      context: node
      target: node
    stdin_open: true
    tty: true
    working_dir: /app
    hostname: 0.0.0.0
    entrypoint:
      - npm
    command:
      - start
    ports:
      - 3000:3000
    volumes:
      - ./node/src:/app/src
      - ./node/public:/app/public
      - /app/node_modules

  app:
    build:
      context: app
      target: app-dev
    stdin_open: true
    tty: true
    command: /bin/bash -c "/bin/wait && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./app:/app/src:cached
      - ./.bash_env:/root:cached

  postgres:
    image: postgres:11.4
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
