# Generated by Django 2.2.7 on 2019-11-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('plr', 'Player'), ('dm', 'DM'), ('obs', 'Observer')], default='plr', max_length=3)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_members', to='parties.Party')),
            ],
        ),
    ]
